#
#  Author: Hari Sekhon
#  Date: 2024-02-27 18:45:11 +0000 (Tue, 27 Feb 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Knowledge-Base
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                     M a r k d o w n   R e f e r e n c e s
# ============================================================================ #

# Check all .md file references exist

---
name: Markdown References

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .github/scripts/check_markdown_references.sh
      - .github/workflows/markdown_references.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .github/scripts/check_markdown_references.sh
      - .github/workflows/markdown_references.yaml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  markdown-references:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: References Check
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        #name: Git Checkout  # better to show the action@version
        with:
          submodules: 'true'  # requires Git 2.18+ to be installed first

      - name: Check all *.md are in the README.md
        run: .github/scripts/check_markdown_references.sh
